### PR TITLE
Install scale to user home

### PR DESCRIPTION
**Pull request by atykhonov**
This PR changes the default installation directory from `/usr/local/` to `$HOME/.scale`. Two executable links (`scale` and `scale-ui`) are installed in `/usr/local/bin/` in the same way as it was.

I was thinking about usage of `$HOME/.config/scale/` and `$HOME/.config/pharo/` directories (instead of `$HOME/.scale`) accordingly to [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). But most of the files which reside in these directories are executables (not user specific configuration files). So I decided to use `$HOME/.scale`. Please, let me know if `$HOME/.config` folder would be more appropriate.

Thank you!

### CODE REVIEW

**Comment by cdlm** [comment]
Installing Scale under `$HOME` but executables in a global place seems contradictory.
What's so bad about requiring the user to setup their `$PATH`?

Also, `/usr/local` is an acceptable install prefix in many cases. I think the install script should be configurable to install Scale in a user-specified prefix, and possibly to rely on an independently installed Pharo; that would cut most of the work for #14.

**Comment by LucFabresse** [comment]
I agree with Damien.
Install it either in /usr/local or in $HOME/.scale.
But we should not mix and the user must set his PATH in the second case.

**Comment by atykhonov** [comment]
Hello @cdlm @LucFabresse !

Sorry for the long delay and thank you very much for your review! You are right, I totally agree with you. So, I've changed everything so that scale is installed into `$HOME/.scale` only.

Please review.

**Comment by LucFabresse** [comment]
Hi, 

Thanks  for this. I think it is better.
Just one question: why did you put it in HOME/.config and not HOME/.scale directly?

Luc

**Comment by guillep** [comment]
Hi @LucFabresse, by reading the diff, I do not see he is using `.config` anymore. However, there is still the example file pwd.st that prints `.config`.

My main question is why removing the install.st file. I understand you could replace it with a `rm -rf`, but 
 - the script was only used in `setupScale.sh` file, but it was meant to be a part of scale's API. In other words, if you want to uninstall scale, you call the uninstall script.
 - in case scale grows in complexity I'd like to have a separate script, even if it just does so far a `rm -rf` inside.
 - I would like it to be written in scale. If we port scale to windows in the future (which is not so crazy to think about), a `rm -rf` solution will not work

**Comment by guillep** [comment]
BTW, related to this, I created issue #20. We should add in our test suite that scale is correctly uninstalled.

**Comment by LucFabresse** [comment]
I look at the wrong diff ;-)
Yes it is better now.


#Luc

2017-03-15 10:05 GMT+01:00 Guillermo <notifications@github.com>:

**Comment by atykhonov** [comment]
> My main question is why removing the install.st file. I understand you could replace it with a rm -rf, but

The main reason why I removed `uninstall.st` is it doesn't work well. After it finishes execution of all code in itself, Pharo' virtual machine throws an error. You could try this by reverting `uninstall.st` and executing it. I have no idea why this error happens and how to resolve it. Any help would be highly appreciated!

**Comment by guillep** [comment]
I'd say that we leave it there for now and then we open a separate issue
about it.

Like that we have smaller and simpler to integrate pull requests.

What do you think?

**Comment by atykhonov** [comment]
I think, ok, no problem. I've reverted the commits that relate to removing of `uninstall.st`. I created issue #21 regarding the error which occurs while uninstallation.

**Comment by atykhonov** [comment]
Btw, uninstallation does its job. What is wrong, is that the error outputs to the console, so that that could be a little bit confusing for a user. Hi might think that uninstallation went wrong.

Does the changes looks good now?

**Comment by guillep** [comment]
I discussed with @sbragagnolo and it looks ok. Thanks!

**Comment by guillep** [comment]
Somehow, this broke the build.

https://travis-ci.org/guillep/Scale/builds/211441475

Which is strange becase the validation against the PR was ok (https://travis-ci.org/guillep/Scale/pull_requests)

**Comment by atykhonov** [comment]
It fails because (I'm looking at https://travis-ci.org/guillep/Scale/jobs/211441477) `scale` could not be found.

It seems that travis job needs to be adjusted, i.e. path to scale needs to be added to PATH.

**Comment by atykhonov** [comment]
I suppose that between these two lines:

```
219 $ sudo ./setupScaleDev.sh
323 $ ./examples/lsst.st
```

we need `export PATH="$HOME/.scale/scale:$PATH"`.

**Comment by guillep** [comment]
Or better

PATH=$PATH:"$HOME/.scale/"

I do no like messing with the precedence.

**Pull request merged**
